#!/usr/bin/env bash

if [[ ! -d include ]] ; then
  echo "chdir to project root, then run as: scripts/ci"
  exit 1
fi

set -xeuo pipefail

export BUILD=build
mkdir -p $BUILD

# Individual unit tests

for UNIT in FD MMap Words ; do
  export PROG="${BUILD}/Test${UNIT}"
  export TESTCC="test/Test${UNIT}.cc"
  COMP=llvm FSAN="-fsanitize=address,undefined" OPT="-Og" ./scripts/buildtest
  $PROG
done

# `TestBinary` tests everything in one go

# TODO: should actually verify symbol names and addresses:
# ~/code/binspect$ for X in test/files/elf*exe ; do for S in $(nm $X | grep ' [TD] ' | sed 's/ [TD] /:/') ; do echo $X $S | tr : ' ' ; done; done
# test/files/elf.32.be.exe 0001020c _start
# test/files/elf.32.be.exe 00010214 main
# test/files/elf.32.le.exe 000011f4 _start
# test/files/elf.32.le.exe 000011f8 main
# test/files/elf.64.be.exe 0000000000030488 _start
# test/files/elf.64.be.exe 00000000000304a0 main
# test/files/elf.64.le.exe 00000000000012f4 _start
# test/files/elf.64.le.exe 00000000000012fa main

# GCC + libstdc++
export PROG="${BUILD}/TestBinary_gcc"
export TESTCC="test/TestBinary.cc"
export OPT="-Os"
export FSAN=""
export COMP="gcc"
./scripts/buildtest
./scripts/runtests

# Using clang with "standard" option set
export PROG="${BUILD}/TestBinary"
export TESTCC="test/TestBinary.cc"
export COMP="llvm"
export OPT="-Og -g"
export FSAN=""
./scripts/buildtest
./scripts/runtests

# ASAN + UBSAN, no optimizations
export PROG="${BUILD}/TestBinary_san_o0"
export TESTCC="test/TestBinary.cc"
export COMP="llvm"
export OPT="-O0 -g"
export FSAN="-fsanitize=address,undefined"
./scripts/buildtest
./scripts/runtests

# ASAN + UBSAN, full optimizations + LTO
# (unsure whether LTO affects much in a header-only lib though)
export PROG="${BUILD}/TestBinary_san_o3lto"
export TESTCC="test/TestBinary.cc"
export COMP="llvm"
export OPT="-O3 -flto -g"
export FSAN="-fsanitize=address,undefined"
./scripts/buildtest
./scripts/runtests

# Without exceptions and RTTI
export PROG="${BUILD}/TestBinary_noexcrtti"
export TESTCC="test/TestBinary.cc"
export OPT="-Os -fno-exceptions -fno-rtti"
export FSAN=""
export COMP="llvm"
./scripts/buildtest
./scripts/runtests
