#!/usr/bin/env bash

if [[ ! -d include ]] ; then
  echo "chdir to project root, then run as: scripts/ci"
  exit 1
fi

set -xeuo pipefail

export BUILD=build
mkdir -p $BUILD

# Individual unit tests

for UNIT in FD MMap Words ; do
  export PROG="${BUILD}/Test${UNIT}"
  export TESTCC="test/Test${UNIT}.cc"
  COMP=llvm FSAN="-fsanitize=address,undefined" OPT="-Og" ./scripts/buildtest
  $PROG
done

# `TestBinary` tests everything, somewhat redundantly, but exercises
# everything in one shot, including things the unit tests above might miss

# Using clang with "standard" option set
export PROG="${BUILD}/TestBinary"
export TESTCC="test/TestBinary.cc"
export COMP="llvm"
export OPT="-Og -g"
export FSAN=""
./scripts/buildtest
./scripts/runtests

# ASAN + UBSAN, no optimizations
export PROG="${BUILD}/TestBinary_san_o0"
export TESTCC="test/TestBinary.cc"
export COMP="llvm"
export OPT="-O0 -g"
export FSAN="-fsanitize=address,undefined"
./scripts/buildtest
./scripts/runtests

# ASAN + UBSAN, full optimizations + LTO
# (unsure whether LTO affects much in a header-only lib though)
export PROG="${BUILD}/TestBinary_san_o3lto"
export TESTCC="test/TestBinary.cc"
export COMP="llvm"
export OPT="-O3 -flto -g"
export FSAN="-fsanitize=address,undefined"
./scripts/buildtest
./scripts/runtests

# GCC + libstdc++
export PROG="${BUILD}/TestBinary_gcc"
export TESTCC="test/TestBinary.cc"
export OPT="-Os"
export FSAN=""
export COMP="gcc"
./scripts/buildtest
./scripts/runtests

# Without exceptions and RTTI
export PROG="${BUILD}/TestBinary_noexcrtti"
export TESTCC="test/TestBinary.cc"
export OPT="-Os -fno-exceptions -fno-rtti"
export FSAN=""
export COMP="llvm"
./scripts/buildtest
./scripts/runtests
