#!/usr/bin/env bash

if [[ ! -d include ]] ; then
  echo "chdir to project root, then run as: scripts/t"
  exit 1
fi

TESTCC=${TESTCC:-test/test_binspect.cc}
BUILD=${BUILD:-build}
PROG=${PROG:-$BUILD/test}
OPT=${OPT:--Og}
FSAN=${FSAN:-}
COMP=${COMP:llvm}

mkdir -p "${BUILD}"

CC=""
if [[ -z $CC && $COMP == llvm ]] ; then CC=$(which clang++) ; fi
if [[ -z $CC && $COMP == llvm ]] ; then CC=$(which clang++-20) ; fi
if [[ -z $CC && $COMP == gcc ]] ; then CC=$(which g++-15) ; fi
if [[ -z $CC && $COMP == gcc ]] ; then CC=$(which g++-14) ; fi

if [[ -z $CC ]] ; then
  echo "need COMP set to 'llvm' or 'gcc', and working clang++/g++"
  exit 1
fi

if [[ $COMP == "gcc" && ! -z $FSAN ]] ; then
  # Won't work on MacOS; just disable this even for CI.
  # We'll test SAN w/ Clang + libc++
  echo "no SAN for g++"
  exit 1
fi

if [[ $COMP == "llvm" ]] ; then
  STDLIB="-stdlib=libc++"
else
  STDLIB=
fi

set -xeuo pipefail

"${CC}"                         \
  @compile_flags.txt            \
  -g                            \
  -UNDEBUG                      \
  ${FSAN} ${OPT} ${STDLIB}      \
  -o "${PROG}"                  \
  "${TESTCC}"
