#!/usr/bin/env bash

if [[ ! -d include ]] ; then
  echo "chdir to project root, then run as: scripts/ci"
  exit 1
fi

export CLANG=${CLANG:-clang++}
export BUILD=build
export PROG="${BUILD}/test"
export TESTCC=test/test_binspect.cc

set -xeuo pipefail

rm -rf build
mkdir build

for COMP in llvm gcc ; do
  COMP=$COMP OPT=-Os SAN= ./scripts/buildtest
  PROG=$PROG ./scripts/runtests
done
