#!/usr/bin/env bash

if [[ ! -d include ]] ; then
  echo "chdir to project root, then run as: scripts/ci"
  exit 1
fi

set -xeuo pipefail

export BUILD=build
mkdir -p $BUILD

for TESTN in error ; do
  export PROG="${BUILD}/test_${TESTN}"
  export TESTCC="test/test_${TESTN}.cc"
  COMP=llvm FSAN="-fsanitize=address,undefined" OPT="-Og" ./scripts/buildtest
  $PROG
done

export PROG="${BUILD}/test"
export TESTCC=test/test_binspect.cc

for COMP in llvm gcc ; do
  COMP=$COMP OPT= FSAN= ./scripts/buildtest
  ./scripts/runtests
done

for FSAN in "-fsanitize=address" "-fsanitize=undefined" ; do
  COMP=llvm OPT=-Os FSAN=$FSAN ./scripts/buildtest
  ./scripts/runtests
done

for OPT in "-fno-exceptions" "-fno-rtti" ; do
  COMP=llvm OPT=$OPT FSAN=$FSAN ./scripts/buildtest
  ./scripts/runtests
done
