#!/usr/bin/env bash

if [[ ! -d include ]] ; then
  echo "chdir to project root, then run as: scripts/pre"
  exit 1
fi

set -xeuo pipefail

# Quick, basic test
# scripts/t

# Automated cleanups + checks
find include/ test/ -type f -name \*.h -o -name \*\.cc \
  | xargs clang-format -i
