#!/usr/bin/env bash

if [[ ! -d include ]] ; then
  echo "chdir to project root, then run as: scripts/pre"
  exit 1
fi

set -xeuo pipefail

export PROG=build/test
export COMP=${COMP:-llvm}
export OPT=${OPT:--O1 -fno-inline}
export SAN=${SAN:-}

scripts/buildtest
$PROG test/files/elf.64.le.exe

# Automated cleanups + checks
find include/ test/ -type f -name \*.h -o -name \*\.cc \
  | xargs clang-format -i
